---
abstract: 'Super simple caching for Catalyst actions'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-ActionRole-PseudoCache
requires:
  Catalyst::Controller::ActionRole: 0.12
  Catalyst::Plugin::Cache: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.80013
  Catalyst::Test: 0
  File::Spec: 0
  FindBin: 0
  Test::More: 0.88
  Test::WWW::Mechanize::Catalyst: 0
  autodie: 0
  parent: 0
resources:
  repository: git://github.com/frioux/Catalyst-ActionRole-PseudoCache.git
version: 1.000003
